name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Unit Tests with Coverage
        run: flutter test --coverage --coverage-path=coverage/lcov.info

      - name: Install test_cov_console
        run: dart pub global activate test_cov_console

      - name: Generate CSV Coverage Report
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          dart pub global run test_cov_console --file=coverage/lcov.info -c

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: pip install pandas matplotlib

      - name: Generate Coverage Visualization
        run: python coverage_visualization.py coverage/test_cov_console.csv

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            coverage/
            coverage_report.png
