name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.5'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Unit Tests with Coverage
        run: flutter test --coverage

      - name: Generate CSV Coverage Report
        run: |
          dart pub global activate test_cov_console
          dart pub global run test_cov_console --file=coverage/lcov.info --multi -c
        env:
          PUB_CACHE: $HOME/.pub-cache

      - name: Upload Coverage Report CSV
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-csv
          path: coverage/test_cov_console_report.csv

      - name: Generate Coverage Graph
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install matplotlib pandas
          python3 scripts/generate_coverage_graph.py
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Upload Coverage Graph
        uses: actions/upload-artifact@v3
        with:
          name: coverage-graph
          path: coverage/coverage_graph.png
